Remove onVisibleChanged dependency
jasp-stats/jaspMixedModels pull request #123
Opened 2023-01-11 14:41 UTC by RensDofferhoff

Fixes: https://github.com/jasp-stats/jasp-test-release/issues/2224
Similar:  https://github.com/jasp-stats/jaspMetaAnalysis/pull/158

2023-01-11 15:00 UTC, JorisGoosen requested changes
Changes mostly look fine, didnt test it but see my requested changes

2023-01-11 15:00 UTC, JorisGoosen commented on inst/qml/MixedModelsBGLMM.qml
> +			property bool active:	family.currentText == "Binomial (aggregated)"
```suggestion
			property bool active:	family.currentText == qsTr("Binomial (aggregated)")
```

2023-01-11 15:00 UTC, JorisGoosen commented on inst/qml/MixedModelsGLMM.qml
> +			property bool active:	family.currentText == "Binomial (aggregated)"
```suggestion
			property bool active:	family.currentText == qsTr("Binomial (aggregated)")
```

2023-01-11 17:34 UTC, FBartos approved these changes
at least the frequentist seems to work (the rstanarm seems to be broken on Linux)

2023-01-12 08:07 UTC, boutinb approved these changes

2023-01-12 10:31 UTC, JorisGoosen approved these changes

2023-01-12 10:31 UTC, merged

2023-01-12 10:34 UTC, RensDofferhoff commented
> rstanarm

You might want to make a new issue for this!